name: Sync pledge

on:
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  cron:
    steps:
      - name: Use Node + Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - name: Sync pledge addresses
        run: node ./.github/workflows/cron/pledge-sync.js
        env:
          GALXE_ACCESS_TOKEN: ${{ secrets.GALXE_ACCESS_TOKEN }}
          FIRESTORE_AUTH: ${{ secrets.FIRESTORE_AUTH }}
